name: Azure Static Web Apps CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    env:
      AzureStaticWebAppsApiToken: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
        displayName: 'Install npm dependencies'

      - script: |
          npm run build
        displayName: 'Build the project'

      - task: AzureStaticWebApp@0
        inputs:
          app_location: '/'
          api_location: 'null'
          output_location: 'dist'
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}